# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Insight
tagline:             'Just a Blog'
description:         ''
url:                 http://samarthbhargav.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Samarth Bhargav
  url:               http://samarthbhargav.github.io
  email:             

# Custom vars
version:             1.0.0

# Build Settings
markdown: redcarpet
