# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Insight
tagline:             'Just a Blog'
description:         'None'
paginate:            5
url:                 http://samarthbhargav.github.io

# About/contact
author:
  name:              Samarth Bhargav
  url:               http://samarthbhargav.github.io
  email:             'http://samarthbhargav.github.io'

# Custom vars
version:             1.0.0

# Build Settings
markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate, kramdown]
pages_list: {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}
